version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: mines-wally_web_1
      APP_PORT: 80
    container_name: mines-wally_app_proxy_1
  web:
    image: >-
      poliuscorp/wally:1.6
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/wally/data
    environment:
      DEMO: 'false'
    container_name: mines-wally_web_1